apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: gcr.io/affable-hall-318421/apitask:v1
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: srv-to-api
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: api

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: srv-to-api
    servicePort: 5000
